Caterer/Controllers/InventoryManagement/ProductManager/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Caterer.Data;
using Caterer.Models;
using System.Security.Claims;
using Microsoft.EntityFrameworkCore;
namespace Caterer.Controllers.InventoryManagement.ProductManager
{
    public class CategoriesController : Controller
    {
        private readonly ApplicationDbContext _context;
        IWebHostEnvironment hostingenvironment;
        public CategoriesController(ApplicationDbContext context, IWebHostEnvironment hc)
        {
            _context = context;
            hostingenvironment = hc;
        }
        // GET: Categories
        public async Task<IActionResult> CategoryList()
        {
            var userEmail = User.FindFirst(ClaimTypes.Email)?.Value;
            var restaurant = await _context.Restaurants
                .FirstOrDefaultAsync(r => r.OwnerEmail == userEmail);
            if (restaurant != null)
            {
                var categories = await _context.Categories
                    .Where(c => c.RestaurantId == restaurant.RestaurantId)  
                           .OrderByDescending(s => s.CategoryId)
                    .ToListAsync();
                return View("~/Views/InventoryManagement/ProductManager/Categories/CategoryList.cshtml", categories);
            }
            return Problem("Entity set 'ApplicationDbContext.Restaurants' is null or user is not associated with any restaurant.");
        }
        // GET: Categories/Details/
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Categories == null)
            {
                return NotFound();
            }
            var categories = await _context.Categories
                .FirstOrDefaultAsync(m => m.CategoryId == id);
            if (categories == null)
            {
                return NotFound();
            }
            return View("~/Views/InventoryManagement/ProductManager/Categories/Details.cshtml", categories);
        }
        //Get Categories
        [HttpGet]
        public IActionResult GetCategories(string term)
        {
            var searchTerm = $"%{term}%";  
            var filteredCategories = _context.Categories
                .FromSqlRaw("SELECT * FROM Categories WHERE CategoryName LIKE {0}", searchTerm)
                .Select(c => new { label = c.CategoryName, value = c.CategoryId })
                .ToList();
            return Json(filteredCategories);
        }
        // GET: Categories/Create
        public IActionResult CategoryCreate()
        {
            var userEmail = User.FindFirst(ClaimTypes.Email)?.Value;
            var restaurant = _context.Restaurants
                .FirstOrDefault(r => r.OwnerEmail == userEmail);
            if (restaurant != null)
            {
                ViewData["RestaurantId"] = restaurant.RestaurantId;
                if (TempData.ContainsKey("DuplicateCategoryError"))
                {
                    ViewData["DuplicateCategoryError"] = TempData["DuplicateCategoryError"];
                }
                return View("~/Views/InventoryManagement/ProductManager/Categories/CategoryCreate.cshtml");
            }
            return RedirectToAction("Index", "Home"); 
        }
        //Post Category Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Consumes("multipart/form-data")]
        public async Task<IActionResult> CategoryCreate(Categoryviewmodel categoryModel, IFormFile ProductImage)
        {
            try
            {
                var userEmail = User.FindFirst(ClaimTypes.Email)?.Value;
                var restaurant = await _context.Restaurants
                    .FirstOrDefaultAsync(r => r.OwnerEmail == userEmail);
                if (restaurant == null)
                {
                    return RedirectToAction("Index", "Home");  
                }
                if (_context.Categories.Any(c => c.CategoryName == categoryModel.CategoryName))
                {
                    TempData["DuplicateCategoryError"] = "Category with the same name already exists.";
                    return RedirectToAction(nameof(CategoryCreate));
                }
                string filename = "";
                if (ProductImage != null)
                {
                    string uploadFolder = Path.Combine(hostingenvironment.WebRootPath, "Images/CategoryImages");
                    filename = Guid.NewGuid().ToString() + "_" + ProductImage.FileName;
                    string filepath = Path.Combine(uploadFolder, filename);
                    using (var fileStream = new FileStream(filepath, FileMode.Create))
                    {
                        await ProductImage.CopyToAsync(fileStream);
                    }
                }
                var category = new Category
                {
                    CategoryName = categoryModel.CategoryName,
                    CategoryLogo = filename, 
                    RestaurantId = restaurant.RestaurantId  
                };
                if (ModelState.IsValid)
                {
                    _context.Add(category);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(CategoryList));
                }
                return View("~/Views/InventoryManagement/ProductManager/Categories/CategoryCreate.cshtml", categoryModel);
            }
            catch (Exception ex)
            {
                return Problem("An error occurred while processing your request. Please try again later.");
            }
        }
        // GET: Categories/Edit/5
        public IActionResult CategoryEdit(int id)
        {
            var category = _context.Categories.Find(id);
            if (category == null)
            {
                return NotFound();
            }
            return View("~/Views/InventoryManagement/ProductManager/Categories/CategoryEdit.cshtml", category);
        }
        //Post Category Edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Consumes("multipart/form-data")]
        public async Task<IActionResult> CategoryEdit(int id, [Bind("CategoryId,CategoryName,CategoryLogo")] Category category, IFormFile ProductImage)
        {
            try
            {
                var existingCategory = _context.Categories.Find(id);
                if (ProductImage != null)
                {
                    if (!string.IsNullOrEmpty(existingCategory.CategoryLogo))
                    {
                        string existingFilePath = Path.Combine(hostingenvironment.WebRootPath, "Images/CategoryImages", existingCategory.CategoryLogo);
                        if (System.IO.File.Exists(existingFilePath))
                        {
                            System.IO.File.Delete(existingFilePath);
                        }
                    }
                    string filename = Guid.NewGuid().ToString() + "_" + ProductImage.FileName;
                    string uploadFolder = Path.Combine(hostingenvironment.WebRootPath, "Images/CategoryImages");
                    string filepath = Path.Combine(uploadFolder, filename);
                    using (var fileStream = new FileStream(filepath, FileMode.Create))
                    {
                        await ProductImage.CopyToAsync(fileStream);
                    }
                    existingCategory.CategoryLogo = filename;
                }
                existingCategory.CategoryName = category.CategoryName;
                _context.Update(existingCategory);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(CategoryList));
            }
            catch (Exception ex)
            {
                return Problem("An error occurred while processing your request. Please try again later.");
            }
        }
        // GET: Categories/Delete/5
        public async Task<IActionResult> CategoryDelete(int? id)
        {
            if (id == null || _context.Categories == null)
            {
                return NotFound();
            }
            var categories = await _context.Categories
                .FirstOrDefaultAsync(m => m.CategoryId == id);
            if (categories == null)
            {
                return NotFound();
            }
            return View("~/Views/InventoryManagement/ProductManager/Categories/CategoryDelete.cshtml", categories);
        }
        // POST: Categories/Delete/5
        [HttpPost, ActionName("CategoryDelete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Categories == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Categories'  is null.");
            }
            var categories = await _context.Categories.FindAsync(id);
            if (categories != null)
            {
                _context.Categories.Remove(categories);
            }
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(CategoryList));
        }
        private bool CategoriesExists(int id)
        {
            return _context.Categories.Any(e => e.CategoryId == id);
        }
    }
}

Caterer/Controllers/InventoryManagement/ProductManager/TaxesController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Caterer.Data;
using Caterer.Data.Migrations;
using Caterer.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.CodeAnalysis;
using Microsoft.EntityFrameworkCore;
namespace Caterer.Controllers.InventoryManagement.ProductManager
{
    public class TaxesController : Controller
    {
        private readonly ApplicationDbContext _context;
        public TaxesController(ApplicationDbContext context)
        {
            _context = context;
        }
        private int GenerateTaxNo()
        {
            var latestTax = _context.Taxes
                .OrderByDescending(t => t.TaxNo)
                .FirstOrDefault();
            int nextCode = 1;
            if (latestTax != null)
            {
                nextCode = latestTax.TaxNo + 1;
            }
            return nextCode;
        }
        // GET: Taxes
        public async Task<IActionResult> TaxList()
        {
            var userEmail = User.FindFirst(ClaimTypes.Email)?.Value;
            var restaurant = await _context.Restaurants
                .FirstOrDefaultAsync(r => r.OwnerEmail == userEmail);
            if (restaurant != null)
            {
                var distinctTaxNumbers = await _context.Taxes
                    .Where(t => t.RestaurantId == restaurant.RestaurantId)  
                    .Select(t => t.TaxNo)
                    .Distinct()
                    .ToListAsync();
                var taxes = new List<Tax>();
                foreach (var taxNo in distinctTaxNumbers)
                {
                    var tax = await _context.Taxes
                        .FirstOrDefaultAsync(t => t.RestaurantId == restaurant.RestaurantId && t.TaxNo == taxNo);
                    if (tax != null)
                    {
                        taxes.Add(tax);
                    }
                }
                return View("~/Views/InventoryManagement/ProductManager/Taxes/TaxList.cshtml", taxes);
            }
            return Problem("Entity set 'ApplicationDbContext.Restaurants' is null or user is not associated with any restaurant.");
        }
        // GET: Taxes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Taxes == null)
            {
                return NotFound();
            }
            var tax = await _context.Taxes
                .FirstOrDefaultAsync(m => m.TaxId == id);
            if (tax == null)
            {
                return NotFound();
            }
            return View("~/Views/Restaurant/ProductManager/Taxes/Details.cshtml", tax);
        }
        // GET: Taxes/Create
        public IActionResult TaxCreate()
        {
            var userEmail = User.FindFirst(ClaimTypes.Email)?.Value;
            var restaurant = _context.Restaurants
                .FirstOrDefault(r => r.OwnerEmail == userEmail);
            if (restaurant != null)
            {
                var tax = new Tax
                {
                };
                ViewData["RestaurantId"] = restaurant.RestaurantId;
                return View("~/Views/InventoryManagement/ProductManager/Taxes/TaxCreate.cshtml", tax);
            }
            return RedirectToAction("Index", "Home");  
        }
        // POST: Taxes/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> TaxCreate([Bind("TaxId,TaxNo,TaxName,TaxType,TaxPercentage,RestaurantId")] Tax tax, List<string> TaxName, List<decimal> TaxPercentage)
        {
            int generatedCode = GenerateTaxNo();
            tax.TaxNo = generatedCode;
            if (ModelState.IsValid)
            {
                bool isDuplicateTaxName = _context.Taxes.Any(t => t.RestaurantId == tax.RestaurantId && t.TaxName == tax.TaxName);
                if (isDuplicateTaxName)
                {
                    ModelState.AddModelError("TaxName", "TaxName already exists.");
                    return View("~/Views/InventoryManagement/ProductManager/Taxes/TaxCreate.cshtml", tax);
                }
                _context.Add(tax);
                for (int i = 0; i < TaxName.Count; i++)
                {
                    if (i == 0)
                        continue;
                    var additionalTax = new Tax
                    {
                        RestaurantId = tax.RestaurantId,
                        TaxId = tax.TaxId,  
                        TaxNo = tax.TaxNo,
                        TaxType = tax.TaxType,
                        TaxName = TaxName[i],
                        TaxPercentage = TaxPercentage[i],
                    };
                    _context.Add(additionalTax);
                }
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(TaxList));
            }

            return View("~/Views/InventoryManagement/ProductManager/Taxes/TaxCreate.cshtml", tax);
        }
        // GET: Taxes/Edit/5
        public async Task<IActionResult> TaxEdit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var tax = await _context.Taxes.FindAsync(id);
            if (tax == null)
            {
                return NotFound();
            }
            var taxesWithSameTaxNo = await _context.Taxes
                .Where(t => t.TaxNo == tax.TaxNo)
                .ToListAsync();
            if (taxesWithSameTaxNo == null || !taxesWithSameTaxNo.Any())
            {
                return NotFound();
            }
            var viewModel = new TaxEditViewModel
            {
                Taxes = taxesWithSameTaxNo
            };
            return View("~/Views/InventoryManagement/ProductManager/Taxes/TaxEdit.cshtml", viewModel);
        }
        // POST: Taxes/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> TaxEdit(List<Tax> taxes)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    foreach (var tax in taxes)
                    {
                        _context.Update(tax);
                    }
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    throw;
                }
                return RedirectToAction(nameof(TaxList));
            }
            return View("~/Views/InventoryManagement/ProductManager/Taxes/TaxEdit.cshtml", taxes);
        }
        // GET: Taxes/Delete/5
        public async Task<IActionResult> TaxDelete(int? taxNo)
        {
            if (taxNo == null)
            {
                return NotFound();
            }
            var taxesWithSameTaxNo = await _context.Taxes
                .Where(m => m.TaxNo == taxNo)
                .ToListAsync();
            if (taxesWithSameTaxNo == null || !taxesWithSameTaxNo.Any())
            {
                return NotFound();
            }
            return View(taxesWithSameTaxNo);
        }
        // POST: Taxes/Delete/5
        [HttpPost, ActionName("TaxDelete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int taxNo)
        {
            Console.WriteLine("DeleteConfirmed action called.");
            var taxesWithSameTaxNo = await _context.Taxes
                .Where(m => m.TaxNo == taxNo)
                .ToListAsync();
            if (taxesWithSameTaxNo == null || !taxesWithSameTaxNo.Any())
            {
                return NotFound();
            }
            _context.Taxes.RemoveRange(taxesWithSameTaxNo);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(TaxList));
        }
        private bool TaxExists(int id)
        {
            return _context.Taxes.Any(e => e.TaxId == id);
        }
    }
}

Caterer/Views/InventoryManagement/ProductManager/Taxes/Details.cshtml
@model Caterer.Models.Tax
@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h1>Details</h1>
<div>
    <h4>Tax</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.TaxNo)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.TaxNo)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.TaxName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.TaxName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.TaxType)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.TaxType)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.TaxPercentage)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.TaxPercentage)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.TaxId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Caterer/Views/InventoryManagement/ProductManager/Taxes/TaxCreate.cshtml
@model Caterer.Models.Tax
@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_CaterersDashboard.cshtml";
}
<div class="container-fluid py-8">
    <div class="row">
        <div class="col-md-5 col-sm-12">
            <div class="card">
                <div class="card-header pb-0">
                    <div class="d-flex justify-content-between align-items-center">
                        <h4>Add Tax</h4>
                        <div class="d-flex">
                            <div class="ms-auto">
                                <a class="btn btn-primary btn-sm ms-auto" asp-action="TaxList" asp-controller="Taxes">Back to List</a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <form asp-action="TaxCreate" method="post">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <div class="row">
                            <input type="hidden" asp-for="TaxNo" value="@Model.TaxNo" />
                            <div class="form-group">
                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <input asp-for="RestaurantId" placeholder="RestaurantId" type="hidden" class="form-control" value="@ViewBag.RestaurantId" />
                                            <label asp-for="TaxType" class="control-label">Tax Type</label>
                                            <select asp-for="TaxType" class="form-control">
                                                <option value="">Select a Tax Type</option>
                                                <option>Single</option>
                                                <option>Multiple</option>
                                            </select>
                                            <span asp-validation-for="TaxType" class="text-danger"></span>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label asp-for="TaxName" class="control-label">Tax Name</label>
                                            <input asp-for="TaxName" class="form-control" placeholder="Please Enter Tax Name" required />
                                            <span asp-validation-for="TaxName" class="text-danger"></span>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label asp-for="TaxPercentage" class="control-label">Tax Percentage %</label>
                                            <input asp-for="TaxPercentage" class="form-control" placeholder="Please Enter Tax Percentage" required />
                                            <span asp-validation-for="TaxPercentage" class="text-danger"></span>
                                        </div>
                                    </div>
                                </div>

                                <div id="additionalTaxFields" style="display: none;">
                                </div>
                                <div class="input-data" id="addNewButtonDiv" style="display: none;">
                                    <button type="button" id="addTaxFieldsButton" class="btn btn-info btn-sm ms-auto"> + Add New </button>
                                </div>
                            </div>
                        </div><br /><br />
                        <div class="row">
                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                <div class="text-center custom-pro-edt-ds">
                                    <button type="submit" class="btn btn-success" onclick="validateName()">
                                        Save
                                    </button>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            @section Scripts {
                @{
                    await Html.RenderPartialAsync("_ValidationScriptsPartial");
                }
                <script>
                    var taxTypeDropdown = document.getElementById("TaxType");
                    var additionalTaxFieldsDiv = document.getElementById("additionalTaxFields");
                    var addNewButtonDiv = document.getElementById("addNewButtonDiv");
                    var addTaxFieldsButton = document.getElementById("addTaxFieldsButton");
                    var taxPercentageInputs = [];
                    function addAdditionalTaxFields() {
                        if (taxTypeDropdown.value === "Multiple") {
                            var taxNameInput = document.createElement("input");
                            taxNameInput.className = "form-control col-md-12";
                            taxNameInput.name = "TaxName";
                            taxNameInput.placeholder = "Please Enter Tax Name";

                            var taxNameLabel = document.createElement("label");
                            taxNameLabel.innerHTML = "Tax Name";
                            taxNameLabel.setAttribute("for", "TaxName");

                            var taxPercentageInput = document.createElement("input");
                            taxPercentageInput.className = "form-control col-md-12";
                            taxPercentageInput.name = "TaxPercentage";
                            taxPercentageInput.placeholder = "Please Enter Tax Percentage";

                            var taxPercentageLabel = document.createElement("label");
                            taxPercentageLabel.innerHTML = "Tax Percentage";
                            taxPercentageLabel.setAttribute("for", "TaxPercentage");

                            taxNameInput.classList.add("placeholder-black");
                            taxPercentageInput.classList.add("placeholder-black");
                            var rowDiv = document.createElement("div");
                            rowDiv.className = "row";
                            var colDiv1 = document.createElement("div");
                            colDiv1.className = "col-md-6";
                            colDiv1.appendChild(taxNameLabel);
                            colDiv1.appendChild(taxNameInput);

                            var colDiv2 = document.createElement("div");
                            colDiv2.className = "col-md-6";
                            colDiv2.appendChild(taxPercentageLabel);
                            colDiv2.appendChild(taxPercentageInput);
                            rowDiv.appendChild(colDiv1);
                            rowDiv.appendChild(colDiv2);
                            var lineBreak = document.createElement("br");

                            taxPercentageInput.addEventListener("input", function () {
                                var total = 0;
                                taxPercentageInputs.forEach(function (input) {
                                    var inputValue = parseInt(input.value);
                                    if (!isNaN(inputValue)) {
                                        total += inputValue;
                                    }
                                });
                                document.querySelector('input[name="TaxPercentage"]').value = total;
                            });
                            additionalTaxFieldsDiv.appendChild(rowDiv);
                            additionalTaxFieldsDiv.appendChild(lineBreak);  
                            taxPercentageInputs.push(taxPercentageInput);
                            additionalTaxFieldsDiv.style.display = "block";
                            addNewButtonDiv.style.display = "block";
                        } else {
                            additionalTaxFieldsDiv.style.display = "none";
                            addNewButtonDiv.style.display = "none";
                            additionalTaxFieldsDiv.innerHTML = "";
                            taxPercentageInputs = [];
                            document.querySelector('input[name="TaxPercentage"]').value = "";
                        }
                    }

                    taxTypeDropdown.addEventListener("change", addAdditionalTaxFields);
                    addTaxFieldsButton.addEventListener("click", addAdditionalTaxFields);
                    addAdditionalTaxFields();
                </script>
            }
        </div>
    </div>
</div>

Caterer/Views/InventoryManagement/ProductManager/Taxes/TaxList.cshtml
@model IEnumerable<Caterer.Models.Tax>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_CaterersDashboard.cshtml";
}
<link rel="stylesheet" href="//cdn.datatables.net/1.13.6/css/jquery.dataTables.min.css">
<div class="container-fluid py-8">
    <div class="row">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-header pb-0">
                    <div class="d-flex justify-content-between align-items-center">
                        <h4> Tax List</h4>
                        <div class="d-flex">
                            <div class="ms-auto">
                                <a class="btn btn-success btn-sm ms-auto" asp-controller="Taxes" asp-action="TaxCreate">Add Tax</a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table id="table" class="table">
                            <thead>
                                <tr>
                                    <th>
                                        S.No
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.TaxName)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.TaxType)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.TaxPercentage)
                                    </th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @{
                                    int counter = 1;
                                }
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>@counter</td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.TaxName)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.TaxType)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.TaxPercentage)
                                        </td>
                                        <td>
                                            <a asp-action="TaxEdit" asp-route-id="@item.TaxId"><i class="fa-solid fa-pen-to-square"></i></a>
                                        </td>
                                        @{
                                            counter++;
                                        }
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@section Scripts {
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.datatables.net/1.13.6/js/jquery.dataTables.js"></script>
    <script>
        $(document).ready(function () {
            $('.table').DataTable({
                "pageLength": 25
            });
        });
    </script>
    }