Caterer/Controllers/InventoryManagement/ProductManager/MeasurementController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Caterer.Data;
using Caterer.Models;
using System.Security.Claims;
using Caterer.Data.Migrations;

namespace Caterer.Controllers.InventoryManagement.ProductManager
{
    public class MeasurementController : Controller
    {
        private readonly ApplicationDbContext _context;
        public MeasurementController(ApplicationDbContext context)
        {
            _context = context;
        }
        // GET: Measurement
        public async Task<IActionResult> MeasurementList()
        {
            var userEmail = User.FindFirst(ClaimTypes.Email)?.Value;
            var restaurant = await _context.Restaurants
                .FirstOrDefaultAsync(r => r.OwnerEmail == userEmail);
            if (restaurant != null)
            {
                var measurements = await _context.Measurements
                    .Where(m => m.RestaurantId == restaurant.RestaurantId)  
                           .OrderByDescending(s => s.MeasurementId)
                    .ToListAsync();
                return View("~/Views/InventoryManagement/ProductManager/Measurement/MeasurementList.cshtml", measurements);
            }
            return Problem("Entity set 'ApplicationDbContext.Restaurants' is null or user is not associated with any restaurant.");
        }
        // GET: Measurement/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Measurements == null)
            {
                return NotFound();
            }
            var measurement = await _context.Measurements
                .FirstOrDefaultAsync(m => m.MeasurementId == id);
            if (measurement == null)
            {
                return NotFound();
            }
            return View(measurement);
        }
        //Post Store
        [HttpPost]
        public JsonResult store(Models.Measurement measurement)
        {
            var pro = new Models.Measurement()
            {
                MeasurementName = measurement.MeasurementName,
                RestaurantId  = measurement.RestaurantId,
            };
            _context.Measurements.Add(pro);
            _context.SaveChanges();
            return new JsonResult("Product Saved Successfully....!");
        }
        //Get Measurement Create
        public IActionResult MeasurementCreate()
        {
            var userEmail = User.FindFirst(ClaimTypes.Email)?.Value;
            var restaurant = _context.Restaurants
                .FirstOrDefault(r => r.OwnerEmail == userEmail);
            if (restaurant != null)
            {
                ViewData["RestaurantId"] = restaurant.RestaurantId;
                if (TempData.ContainsKey("ErrorMessage"))
                {
                    ViewData["ErrorMessage"] = TempData["ErrorMessage"];
                }
                return View("~/Views/InventoryManagement/ProductManager/Measurement/MeasurementCreate.cshtml");
            }
            return RedirectToAction("Index", "Home");  
        }

        // POST: Measurement/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> MeasurementCreate([Bind("MeasurementId,MeasurementName")] Models.Measurement measurement)
        {
            try
            {
                var userEmail = User.FindFirst(ClaimTypes.Email)?.Value;
                var restaurant = await _context.Restaurants
                    .FirstOrDefaultAsync(r => r.OwnerEmail == userEmail);
                if (restaurant == null)
                {
                    return RedirectToAction("Index", "Home");  
                }
                measurement.RestaurantId = restaurant.RestaurantId;
                if (_context.Measurements.Any(m => m.MeasurementName == measurement.MeasurementName))
                {
                    ModelState.AddModelError("MeasurementName", "Measurement name already exists.");
                    return View("~/Views/InventoryManagement/ProductManager/Measurement/MeasurementCreate.cshtml", measurement);
                }
                if (ModelState.IsValid)
                {
                    _context.Add(measurement);
                    await _context.SaveChangesAsync();
                    return RedirectToAction("MeasurementList","Measurement");
                }
                return View("~/Views/InventoryManagement/ProductManager/Measurement/MeasurementCreate.cshtml", measurement);
            }
            catch (Exception ex)
            {
                return Problem("An error occurred while processing your request. Please try again later.");
            }
        }
        // GET: Measurement/Edit/5
        public async Task<IActionResult> MeasurementEdit(int? id)
        {
            if (id == null || _context.Measurements == null)
            {
                return NotFound();
            }
            var measurement = await _context.Measurements.FindAsync(id);
            if (measurement == null)
            {
                return NotFound();
            }
            return View("~/Views/InventoryManagement/ProductManager/Measurement/MeasurementEdit.cshtml", measurement);
        }
        // POST: Measurement/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> MeasurementEdit(int id, [Bind("MeasurementId,MeasurementName,RestaurantId")] Models.Measurement measurement)
        {
            if (id != measurement.MeasurementId)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(measurement);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MeasurementExists(measurement.MeasurementId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(MeasurementList));
            }
            return View("~/Views/InventoryManagement/ProductManager/Measurement/MeasurementEdit.cshtml", measurement);
        }
        // GET: Measurement/Delete/5
        public async Task<IActionResult> MeasurementDelete(int? id)
        {
            if (id == null || _context.Measurements == null)
            {
                return NotFound();
            }
            var measurement = await _context.Measurements
                .FirstOrDefaultAsync(m => m.MeasurementId == id);
            if (measurement == null)
            {
                return NotFound();
            }
            return View("~/Views/InventoryManagement/ProductManager/Measurement/MeasurementDelete.cshtml", measurement);
        }
        // POST: Measurement/Delete/5
        [HttpPost, ActionName("MeasurementDelete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Measurements == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Measurement'  is null.");
            }
            var measurement = await _context.Measurements.FindAsync(id);
            if (measurement != null)
            {
                _context.Measurements.Remove(measurement);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(MeasurementList));
        }
        private bool MeasurementExists(int id)
        {
            return (_context.Measurements?.Any(e => e.MeasurementId == id)).GetValueOrDefault();
        }
    }
}

Caterer/Controllers/InventoryManagement/PurchaseOrdersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Caterer.Data;
using Caterer.Models;
using System.Security.Claims;
using Microsoft.AspNetCore.Http;
using Caterer.Data.Migrations;
using Microsoft.CodeAnalysis;
namespace Caterer.Controllers.InventoryManagement
{
    public class PurchaseOrdersController : Controller
    {
        private readonly ApplicationDbContext _context;
        public PurchaseOrdersController(ApplicationDbContext context)
        {
            _context = context;
        }
        // GET: PurchaseOrder
        public async Task<IActionResult> PurchaseOrderList(int? warehouseId)
        {
            var userEmail = User.FindFirst(ClaimTypes.Email)?.Value;
            var restaurant = await _context.Restaurants
                .FirstOrDefaultAsync(r => r.OwnerEmail == userEmail);

            if (restaurant != null)
            {
                var warehouses = _context.Warehouses
                    .Where(w => w.RestaurantId == restaurant.RestaurantId)
                    .ToList();

                IQueryable<PurchaseOrder> purchaseOrders = _context.PurchaseOrders
                  .Where(p => p.RestaurantId == restaurant.RestaurantId)
                  .Include(p => p.Supplier)
                  .OrderByDescending(s => s.PurchaseOrderId);

                ViewData["Warehouses"] = warehouses;

                if (!warehouseId.HasValue)
                {
                    var defaultWarehouse = warehouses.FirstOrDefault();
                    warehouseId = defaultWarehouse?.WarehouseId;
                }
                if (warehouseId.HasValue)
                {
                    purchaseOrders = purchaseOrders.Where(p => p.WarehouseId == warehouseId.Value);
                }
                var products = await purchaseOrders.ToListAsync();
                return View("~/Views/InventoryManagement/PurchaseOrders/PurchaseOrderList.cshtml", products);
            }
            return Problem("Entity set 'ApplicationDbContext.Restaurants' is null or user is not associated with any restaurant.");
        }
        //Supplier Popup Create
        [HttpPost]
        public JsonResult SaveSupplier([Bind("SupplierId,SupplierName,RestaurantId,WarehouseId,Email,PhoneNumber,Status,OpeningBalance,CreditPeriod,CreditLimit,ShippingAddress,BillingAddress")] Supplier Suppliermodel)
        {
            var supplier = new Supplier
            {
                RestaurantId = Suppliermodel.RestaurantId,
                WarehouseId = Suppliermodel.WarehouseId,
                SupplierName = Suppliermodel.SupplierName,
                PhoneNumber = Suppliermodel.PhoneNumber,
                Email = Suppliermodel.Email,
                Status = Suppliermodel.Status,
                OpeningBalance = Suppliermodel.OpeningBalance,
                CreditPeriod = Suppliermodel.CreditPeriod,
                CreditLimit = Suppliermodel.CreditLimit,
                BillingAddress = Suppliermodel.BillingAddress,
                ShippingAddress = Suppliermodel.ShippingAddress
            };
            _context.Suppliers.Add(supplier);
            _context.SaveChanges();
            return Json(supplier.SupplierId);
        }
        // GET: PurchaseOrder/Details/5
        public async Task<IActionResult> PurchaseOrderDetails(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var purchaseOrder = await _context.PurchaseOrders
                .Where(p => p.PurchaseOrderId == id)
                .Include(a => a.Supplier)
                .FirstOrDefaultAsync();
            if (purchaseOrder == null)
            {
                return NotFound();
            }
            var purchaseOrderNo = purchaseOrder.PurchaseOrderNo;
            var relatedPurchaseOrders = await _context.PurchaseOrders
                .Where(p => p.PurchaseOrderNo == purchaseOrderNo)
                .ToListAsync();
            var relatedGRNs = await _context.GRNS
                .Where(g => g.PurchaseOrderNo == purchaseOrderNo)
                .ToListAsync();
            var query = from po in _context.PurchaseOrders
                        join supplier in _context.Suppliers on po.SupplierId equals supplier.SupplierId
                        select new Supplier
                        {
                            SupplierId = supplier.SupplierId,
                            SupplierName = supplier.SupplierName,
                            ShippingAddress = supplier.ShippingAddress,
                            PhoneNumber = supplier.PhoneNumber,
                            Email = supplier.Email,
                        };
            var purchaseOrders = query.ToList();
            ViewData["RelatedPurchaseOrders"] = relatedPurchaseOrders;
            ViewData["RelatedGRNs"] = relatedGRNs;
            ViewData["RelatedPurchaseOrder"] = purchaseOrder;
            return View("~/Views/InventoryManagement/PurchaseOrders/PurchaseOrderDetails.cshtml", purchaseOrder);
        }
        //PNo Number 
        private int GenerateAutomaticPNo()
        {
            var maxPNo = _context.PurchaseOrders.Max(po => (int?)po.PNo) ?? 0;
            return maxPNo + 1;
        }
        //Po Order No
        private string GenerateAutomaticPurchaseOrderNo()
        {
            var maxPurchaseOrderNo = _context.PurchaseOrders.Max(po => po.PurchaseOrderNo);
            if (!string.IsNullOrEmpty(maxPurchaseOrderNo) && maxPurchaseOrderNo.StartsWith("PO-"))
            {
                var numericPart = maxPurchaseOrderNo.Substring(3);
                if (int.TryParse(numericPart, out var maxNumber))
                {
                    var newNumber = (maxNumber + 1).ToString("D4");
                    return $"PO-{newNumber}";
                }
            }
            return "PO-1000";
        }
        //ProductName Search
        [HttpGet]
        public IActionResult SearchProduct(string searchTerm, int warehouseId)
        {
            var userEmail = User.FindFirst(ClaimTypes.Email)?.Value;
            var restaurant = _context.Restaurants.FirstOrDefault(r => r.OwnerEmail == userEmail);
            if (restaurant != null)
            {
                var productNames = _context.Products
                    .Where(p =>
                        (p.ProductName.StartsWith(searchTerm) || p.Barcode.StartsWith(searchTerm)) &&
                        p.WarehouseId == warehouseId &&
                        p.RestaurantId == restaurant.RestaurantId)
                    .Select(p => p.ProductName)
                    .ToList();
                return Json(productNames);
            }
            return Json(new List<string>());
        }
        //GET Product Details
        public IActionResult GetProductDetails(string productId)
        {
            if (string.IsNullOrEmpty(productId))
            {
                return Json(null);
            }
            var productDetails = _context.Products
                .Include(p => p.Measurement)
                .FirstOrDefault(p => p.ProductName == productId);
            if (productDetails != null)
            {
                var productData = new
                {
                    measurementId = productDetails.MeasurementId,
                    measurementName = productDetails.Measurement?.MeasurementName,
                    inStock = productDetails.Instock,
                    unitCost = productDetails.UnitCost,

                };
                return Json(productData);
            }
            return Json(null);
        }
        // GET: PurchaseOrder/Create
        public IActionResult PurchaseOrderCreate()
        {
            ViewBag.Warehouses = new SelectList(_context.Warehouses, "WarehouseId", "WarehouseName");
            var userEmail = User.FindFirst(ClaimTypes.Email)?.Value;
            var restaurant = _context.Restaurants
                .FirstOrDefault(r => r.OwnerEmail == userEmail);
            if (restaurant != null)
            {
                var suppliers = _context.Suppliers
                    .Where(s => s.RestaurantId == restaurant.RestaurantId)
                 .Select(w => new SelectListItem
                 {
                     Value = w.SupplierId.ToString(),
                     Text = w.SupplierName
                 })
                   .ToList();
                ViewData["Suppliers"] = suppliers;
                var warehouses = _context.Warehouses
                  .Where(w => w.RestaurantId == restaurant.RestaurantId)
                  .Select(w => new SelectListItem
                  {
                      Value = w.WarehouseId.ToString(),
                      Text = w.WarehouseName
                  })
                  .ToList();
                ViewData["Warehouses"] = warehouses;
                var purchaseorder = new PurchaseViewModel()
                {
                    PurchaseOrderNo = GenerateAutomaticPurchaseOrderNo(),
                    RestaurantId = restaurant.RestaurantId
                };
                purchaseorder.PNo = GenerateAutomaticPNo();
                ViewData["RestaurantId"] = restaurant.RestaurantId;
                return View("~/Views/InventoryManagement/PurchaseOrders/PurchaseOrderCreate.cshtml", purchaseorder);
            }
            return RedirectToAction("Index", "Home");
        }
        //Purchase Order Create
        [HttpPost]
        [ValidateAntiForgeryToken]

Caterer/Views/InventoryManagement/PurchaseOrders/PurchaseOrderDetails.cshtml
@model Caterer.Models.PurchaseOrder
@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_CaterersDashboard.cshtml";
    ViewData["Heading"] = "Purchase Order";
}
<div class="container-fluid py-8">
    <div class="row">
        <div class="col-10">
            <div class="card">
                <div class="card-header pb-0">
                    <div class="d-flex justify-content-between align-items-center">
                        <h4>Purchase Order Details</h4>
                        <div class="d-flex">
                            <div class="ms-auto">
                                <a class="btn btn-primary btn-sm ms-auto" asp-controller="PurchaseOrders" asp-action="PurchaseOrderList">Back to List</a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="col-md-6">
                            <table style="width:100%;">

                                <tr>
                                    <td class="align-right" style="color: midnightblue;font-weight:600;">Supplier : @Model.Supplier.SupplierName</td>
                                </tr>
                                <tr>
                                    <td class="align-right">@Model.Supplier.ShippingAddress</td>
                                </tr>
                                <tr>
                                    <td class="align-right">@Model.Supplier.PhoneNumber</td>
                                </tr>
                                <tr>
                                    <td class="align-right">@Model.Supplier.Email</td>
                                </tr>
                            </table>

                        </div>
                        <div class="d-flex">
                            <div class="ms-auto">
                                <div class="text-right btn-sm ms-auto">

                                    <table style="width:100%;">

                                        <tr>
                                            <td><h5>Po No: @Model.PurchaseOrderNo</h5></td>
                                        </tr>
                                        <tr>
                                            <th style="text-align: left;">Order Date</th>
                                            <td class="align-right">@(Model.PurchaseOrderDate.ToString("dd-MM-yyyy" ?? "N/A"))</td>
                                        </tr>
                                        <tr>
                                            <th style="text-align: left;">Expected Date:</th>
                                            <td class="align-right">@(Model.ExpectedDate.ToString("dd-MM-yyyy" ?? "N/A"))</td>
                                        </tr>
                                        <tr>
                                            <th style="text-align: left;">Payment Method:</th>
                                            <td class="align-right">@Model.Paymentmethod</td>
                                        </tr>
                                        <tr>
                                            <th style="text-align: left;">Delivery Instructions:</th>
                                            <td class="align-right">@Model.DeliveryInstruction</td>
                                        </tr>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="table-responsive">
                    <table class="table" style="margin-top:50PX;">
                        <thead>
                            <tr>
                                    <th>S.No</th>
                                <th>Product Name</th>
                                <th>Measurement</th>
                                <th>Quantity</th>
                                <th>Unit Cost</th>
                                <th>Total Cost</th>
                            </tr>
                        </thead>
                        <tbody>
                                @{
                                    int counter = 1;
                                }
                            @foreach (var relatedPurchaseOrder in (List<Caterer.Models.PurchaseOrder>)ViewData["RelatedPurchaseOrders"])
                            {
                                <tr>
                                        <td>@counter</td>
                                    <td>@relatedPurchaseOrder.ProductName</td>
                                    <td>@relatedPurchaseOrder.Measurement</td>
                                    <td>
                                        @*@if (relatedPurchaseOrder.Quantity == 0)
                                    {
                                    @Html.Raw("-")
                                    }
                                    else
                                    {
                                    @string.Format("{0:0.###}", relatedPurchaseOrder.Quantity)
                                    }*@
                                        @relatedPurchaseOrder.Quantity
                                    </td>
                                    <td>@relatedPurchaseOrder.UnitCost</td>
                                    <td>@relatedPurchaseOrder.TotalCost</td>
                                        @{
                                            counter++;
                                        }
                                </tr>
                            }
                        </tbody>
                    </table>
                    </div>
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="col-md-12" style="width:100%;margin-top:20PX;padding-right:25PX;">
                            <div class="d-flex">
                                <div class="ms-auto">
                                    <div class="text-right btn-sm ms-auto">
                                        <div class="total">
                                            <div><h6>Total Amount:  <strong> @Model.Total</strong></h6></div>

                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                    </div>
                    <div class="col-md-4">
                        @if (Model.Status == "Pending" && ViewData["RelatedGRNs"] != null && ((List<Caterer.Models.GRN>)ViewData["RelatedGRNs"]).Any())
                        {
                            <p>Status: Partially Completed</p>
                        }
                        else
                        {
                            <p>Status: @Model.Status</p>
                        }
                    </div>
                    <h5>Received GRN</h5>
                    <div class="table-responsive">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>GRN No</th>
                                <th>ProductName</th>
                                <th>GRN Date</th>
                                <th>Quantity</th>
                              @*  <th>Balance</th>*@
                                <th>Status</th>
                            </tr>
                        </thead>
                        <tbody>
                            @{
                                // Initialize a dictionary to store the total GRN quantity for each product
                                Dictionary<string, int> totalGRNQuantities = new Dictionary<string, int>();
                            }

                            @foreach (var relatedGRN in (List<Caterer.Models.GRN>)ViewData["RelatedGRNs"])
                            {
                                <tr>
                                    <td>@relatedGRN.GRNNO</td>
                                    <td>@relatedGRN.ProductName</td>
                                    <td>@relatedGRN.GRNDate.ToString("MM/dd/yyyy")</td>
                                    <td>@relatedGRN.Quantity</td>

                                    @{
                                        // Check if the product is already in the dictionary
                                        if (!totalGRNQuantities.ContainsKey(relatedGRN.ProductName))
                                        {
                                            totalGRNQuantities[relatedGRN.ProductName] = 0;
                                        }

                                        // Accumulate the GRN quantities for each product
                                        totalGRNQuantities[relatedGRN.ProductName] += (int)relatedGRN.Quantity;
                                    }

                                  @*  <td>@(totalGRNQuantities[relatedGRN.ProductName] - Model.Quantity)</td>*@ <!-- Calculate and display the balance -->
                                    <td>
                                        <p>@Model.Status</p>
                                    </td>
                                    <td>
                                    </td>
                                    <!-- Add more cells as needed -->
                                </tr>
                            }
                        </tbody>
                    </table>
                    </div>
                    <br />
                    <br />
                    <div class="row">
                        <div class="col-md-4">
                            <div class="signature">
                                <div class="signature-line">
                                    <span class="signature-label"><b>Store Keeper Signature:</b></span>
                                    <div class="signature-box"></div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="signature">
                                <div class="signature-line">
                                    <span class="signature-label"><b>Approved by</b></span>
                                    <div class="signature-box"></div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="signature">
                                <div class="signature-line">
                                    <span class="signature-label"><b>Received by:</b></span>
                                    <div class="signature-box"></div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <br />
                    <div>
                        <div class="row">
                            <div class="col-md-4">
                                @if (Model.Status == "Pending")
                                {
                                    <!-- Your content for the first column -->
                                }
                            </div>
                            <div class="col-md-4 text-center">
                                <div class="text-center custom-pro-edt-ds">
                                    @if (Model.Status == "Pending")
                                    {
                                        <a asp-action="CreateGRN" asp-controller="GRNs"
                                           asp-route-total="@Model.Total"
                                           asp-route-purchaseOrderNo="@Model.PurchaseOrderNo"
                                           asp-route-purchaseOrderDate="@Model.PurchaseOrderDate.ToString("yyyy-MM-dd")"
                                           asp-route-supplierId="@Model.SupplierId"
                                           asp-route-paymentMethod="@Model.Paymentmethod"
                                           class="btn btn-success">Create GRN</a>
                                        <button id="printButton" class="btn btn-success ml-2">
                                            Print
                                        </button>
                                    }
                                    else if (Model.Status == "Partially")
                                    {
                                        <a asp-action="CreateUpdateGRN" asp-controller="GRNs"
                                           asp-route-total="@Model.Total"
                                           asp-route-purchaseOrderNo="@Model.PurchaseOrderNo"
                                           asp-route-purchaseOrderDate="@Model.PurchaseOrderDate.ToString("yyyy-MM-dd")"
                                           asp-route-supplierId="@Model.SupplierId"
                                           asp-route-paymentMethod="@Model.Paymentmethod"
                                           class="btn btn-success">Create GRN</a>
                                        <button id="printButton" class="btn btn-success ml-2">
                                            Print
                                        </button>
                                    }
                                </div>
                            </div>
                        </div>
                      


                    </div>
                </div>
            </div>
            @section Scripts {

                @{
                    await Html.RenderPartialAsync("_ValidationScriptsPartial");
                }
            }
        </div>
    </div>
</div>