Caterer/Models/Production.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
namespace Caterer.Models
{
    public class Production
    {
        [Key]
        public int ProductionId { get; set; }
        public DateTime? ProductionDate { get; set; }
        [DisplayName("Production Status")]
        public string? ProductionStatus { get; set; }
        public int OrderDetailsWebsiteId { get; set; }
        [DisplayName("Order Status")]
        public string? OrderStatus { get; set; }
        public int RestaurantId { get; set; }
        [DisplayName("Main Category")]
        public int CateringCategoryId { get; set; }
        [DisplayName("Total Number of Packs")]
        public int TotalNoOfPacks { get; set; }
        [DisplayName("Extra Menu Packs")]
        public int ExtraPacks { get; set; }
        public int MenuItemId { get; set; }
        [DisplayName("Menu Category")]
        public string MenuCategory { get; set; }
        [DisplayName("Item Name")]
        public string MenuItemName { get; set; }
        public int ProductId { get; set; }
        [DisplayName("Product Name")]
        public string ProductName { get; set; }
        [DisplayName("Product Category")]
        public string ProductCategory { get; set; }
        [DisplayName("Product Type")]
        public string ProductType { get; set; }
        [DisplayName("Unit")]
        public string ProductUnit { get; set; }
        [DisplayName("Pre-Preparing Packs")]
        public int MenuRecipePacks { get; set; }
        [DisplayName("Quantity")]
        public decimal? MenuRecipeQty { get; set; }
        public decimal? UsedQuantity { get; set; } = null;
        public decimal? TotalQuantity { get; set; } = null;
        public int? WarehouseId { get; set; }
        public string ProductCode { get; set; }
    }
}

Caterer/Controllers/ProductionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Caterer.Data;
using Caterer.Models;
using System.Security.Claims;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.Data.SqlClient;
using System.Data;
using System.Linq;
using Caterer.Data.Migrations;
using Microsoft.CodeAnalysis;
namespace Caterer.Controllers
{
    public class ProductionsController : Controller
    {
        private readonly ApplicationDbContext _context;
        public ProductionsController(ApplicationDbContext context)
        {
            _context = context;
        }
        //Details
        public async Task<IActionResult> ProductionDetails(int id)
        {
            var userEmail = User.FindFirst(ClaimTypes.Email)?.Value;
            var restaurant = _context.Restaurants.FirstOrDefault(r => r.OwnerEmail == userEmail);
            if (restaurant != null)
            {
                var warehouse = _context.Warehouses.Where(p => p.RestaurantId == restaurant.RestaurantId).ToList();
                ViewBag.warehouse = new SelectList(warehouse, "WarehouseId", "WarehouseName");
            }
            var orderDetails = _context.OrderDetailWebsites
                                        .Where(o => o.OrderDetailsWebsiteId == id)
                                        .ToList();
            if (orderDetails.Count == 0)
            {
                return NotFound();
            }
            ViewBag.OrderDetailsWebsiteId = id;
            var productions = (from a in orderDetails
                               from b in _context.Productions.ToList()
                               join warehouse in _context.Warehouses.ToList()
                               on b.WarehouseId equals warehouse.WarehouseId
                               where a.CateringItemId.Split(',').Contains(b.MenuItemId.ToString()) && a.OrderDetailsWebsiteId == b.OrderDetailsWebsiteId
                               select new
                               {
                                   b.ProductionDate,
                                   b.ProductionStatus,
                                   b.OrderDetailsWebsiteId,
                                   b.CateringCategoryId,
                                   b.RestaurantId,
                                   b.OrderStatus,
                                   b.MenuItemId,
                                   b.MenuCategory,
                                   b.MenuRecipePacks,
                                   b.TotalNoOfPacks,
                                   b.ProductId,
                                   b.ProductCode,
                                   b.ProductUnit,
                                   b.MenuItemName,
                                   b.MenuRecipeQty,
                                   b.ProductName,
                                   b.ProductCategory,
                                   b.ProductType,
                                   b.UsedQuantity,
                                   b.TotalQuantity,
                                   b.WarehouseId,
                                   warehouse.WarehouseName
                               }).ToList();
            var firstProduction = productions.FirstOrDefault();
            ViewBag.FirstProduction = firstProduction;
            var productions1 = (from a in orderDetails
                                from b in _context.Productions
                                let extrasCateringItemIds = a.ExtraCateringItemId.Split(',').ToList()
                                let extraCateringNoOfPax = a.ExtraNoOfPax.Split(',')
                                                    .Select(s => { int.TryParse(s, out int result); return result; })
                                                    .ToList()
                                let zipped = extrasCateringItemIds.Zip(extraCateringNoOfPax, (itemId, pax) => new { ItemId = itemId, Pax = pax })
                                from c in zipped
                                where b.MenuItemId.ToString() == c.ItemId && a.OrderDetailsWebsiteId == b.OrderDetailsWebsiteId
                                select new
                                {
                                    b.OrderDetailsWebsiteId,
                                    b.CateringCategoryId,
                                    b.RestaurantId,
                                    b.OrderStatus,
                                    b.MenuItemId,
                                    b.MenuCategory,
                                    b.MenuRecipePacks,
                                    b.TotalNoOfPacks,                                    
                                    b.ProductId,
                                    b.ProductCode,
                                    b.ProductUnit,
                                    b.MenuItemName,
                                    b.MenuRecipeQty,
                                    b.ProductName,
                                    b.ProductCategory,
                                    b.ProductType,
                                    b.UsedQuantity,
                                    b.TotalQuantity,
                                    b.WarehouseId,
                                }).ToList();
            var productions2 = (from a in orderDetails
                                from b in _context.Productions
                                let extrasCateringItemIds = a.ExtrasCateringItemId.Split(',').ToList()
                                let extraCateringNoOfPax = a.ExtraCateringNoOfPax.Split(',')
                                                    .Select(s => { int.TryParse(s, out int result); return result; })
                                                    .ToList()
                                let zipped = extrasCateringItemIds.Zip(extraCateringNoOfPax, (itemId, pax) => new { ItemId = itemId, Pax = pax })
                                from c in zipped
                                where b.MenuItemId.ToString() == c.ItemId && a.OrderDetailsWebsiteId == b.OrderDetailsWebsiteId
                                select new
                                {
                                    b.OrderDetailsWebsiteId,
                                    b.CateringCategoryId,
                                    b.RestaurantId,
                                    b.OrderStatus,
                                    b.MenuItemId,
                                    b.MenuCategory,
                                    b.MenuRecipePacks,
                                    b.TotalNoOfPacks,
                                    b.ProductId,
                                    b.ProductCode,
                                    b.ProductUnit,
                                    b.MenuItemName,
                                    b.MenuRecipeQty,
                                    b.ProductName,
                                    b.ProductCategory,
                                    b.ProductType,
                                    b.UsedQuantity,
                                    b.TotalQuantity,
                                    b.WarehouseId,
                                    b.ExtraPacks
                                }).ToList();
            ViewBag.OrderMenus = productions;
            ViewBag.MenuAdjustment = productions1;
            ViewBag.ExtraOrderMenu = productions2;
            return View();
        }
        //Index
        public async Task<IActionResult> ProductionIndex()
        {
            var userEmail = User.FindFirst(ClaimTypes.Email)?.Value;
            var restaurant = await _context.Restaurants.FirstOrDefaultAsync(r => r.OwnerEmail == userEmail);
            if (restaurant != null)
            {
                var productions = await _context.Productions
                    .Where(p => p.RestaurantId == restaurant.RestaurantId)
                    .GroupBy(p => p.OrderDetailsWebsiteId)
                    .Select(g => g.First())
                    .ToListAsync();
                if (productions.Any())
                {
                    return View(productions);
                }
            }
            return View();
        }
        //Get Create
        public IActionResult ProductionCreate(int id)
        {
            var userEmail = User.FindFirst(ClaimTypes.Email)?.Value;
            var restaurant = _context.Restaurants.FirstOrDefault(r => r.OwnerEmail == userEmail);
            if (restaurant != null)
            {
                var warehouse = _context.Warehouses.Where(p => p.RestaurantId == restaurant.RestaurantId).ToList();
                ViewBag.warehouse = new SelectList(warehouse, "WarehouseId", "WarehouseName");
            }
            var orderDetails = _context.OrderDetailWebsites
                                        .Where(o => o.OrderDetailsWebsiteId == id)
                                        .ToList();
            if (orderDetails.Count == 0)
            {
                return NotFound();
            }
            var productions = (from a in orderDetails
                               from b in _context.MenuRecipes
                               where a.CateringItemId.Split(',').Contains(b.MenuItemId.ToString())
                               select new
                               {
                                   a.OrderDetailsWebsiteId,
                                   a.CateringCategoryId,
                                   a.RestaurantId,
                                   a.Status,
                                   a.CateringItemId,
                                   a.NoOfPerson,
                                   b.MenuItemId,
                                   b.MenuCategory,
                                   b.Packs,
                                   b.ProductId,

Caterer/Views/Productions/ProductionIndex.cshtml
@model IEnumerable<Caterer.Models.Production>
@{

    Layout = "~/Views/Shared/_CaterersDashboard.cshtml";
}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
<link rel="stylesheet" href="//cdn.datatables.net/1.13.6/css/jquery.dataTables.min.css">
<div class="container-fluid py-8">
    <div class="row">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-header pb-0">
                    <div class="d-flex justify-content-between align-items-center">
                        <h4>Production Orders</h4>
                    </div>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table id="table" class="table">
                            <thead>
                                <tr>
                                    <th>S.No</th>
                                    <th>Production Date</th>
                                    <th>Production Status</th>
                                    <th>Order Status</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @if (Model != null && Model.Any())
                                {
                                    int Slno = 1;
                                    foreach (var item in Model)
                                    {
                                        <tr>
                                            <td>@Slno</td>
                                            <td>@(item.ProductionDate.HasValue ? item.ProductionDate.Value.ToString("dd-MM-yyyy") : "")</td>

                                            <td>
                                                @if (item.ProductionStatus == "Process")
                                                {
                                                    <span class="badge badge-secondary" style="background-color: red; color: white;">@item.ProductionStatus</span>

                                                }
                                                else if (item.ProductionStatus == "Completed")
                                                {
                                                    <span class="badge badge-secondary" style="background-color: green; color: white;">@item.ProductionStatus</span>
                                                }

                                            </td>
                                            <td>
                                                @if (item.OrderStatus == "Accept")
                                                {
                                                    <span class="badge badge-secondary" style="background-color: green; color: white;">@item.OrderStatus</span>
                                                }
                                            <td>
                                                @if (item.ProductionStatus != "Completed")
                                                {
                                                    <a asp-action="ProductionEdit" asp-controller="Productions" asp-route-id="@item.OrderDetailsWebsiteId"><i class="fa-solid fa-pen-to-square"></i></a>
                                                }
                                                else
                                                {
                                                    <span style="color: grey;"><i class="fa-solid fa-pen-to-square"></i></span>
                                                }|
                                                <a asp-action="ProductionDetails" asp-controller="Productions" asp-route-id="@item.OrderDetailsWebsiteId">
                                                    <i class="fa-solid fa-eye"></i>
                                                </a>
                                            </td>
                                        </tr>
                                        Slno++;
                                    }
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@section Scripts {
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.datatables.net/1.13.6/js/jquery.dataTables.js"></script>
    <script>
        $(document).ready(function () {
            $('.table').DataTable({
                "pageLength": 25
            });
        });
    </script>
    }