Caterer/Models/PreProduction.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Composition;
namespace Caterer.Models
{
    public class PreProduction
    {
        [Key]
        public int PreProductionId { get; set; }
        [DisplayName("Status")]
        public string? PreProductionStatus { get; set; }
        public string? Type { get; set; }
        [DisplayName("Prepared Date")]
        public DateTime? PreProductionDate { get; set; }
        [DisplayName("Expiry Date")]
        public DateTime? ExpiryDate { get; set; }
        public int? RestaurantId { get; set; }
        [DisplayName("Warehouse  Name")]
        public int? WarehouseId { get; set; }
        [Required]
        public string MenuItemId { get; set; }
        [DisplayName("Recipe  Name")]
        public string? MenuItemName { get; set; }
        public int? Packs { get; set; }
        [DisplayName("Category")]
        public string? MenuCategory { get; set; }
        public string ProductId { get; set; }
        [DisplayName("Product Code")]
        public string? Productcode { get; set; }
        public string? ProductName { get; set; }
        [DisplayName("Unit")]
        public string? ProductUnit { get; set; }
        [DisplayName("Category")]
        public string? ProductCategory { get; set; }
        [Required]
        [DisplayName("Recipe Qty")]
        public decimal MenuRecipeQty { get; set; }
        [DisplayName("ProductType")]
        public string ProductType { get; set; }
        public decimal TotalQuantity { get; set; }
        [DisplayName("Total Production Packs")]
        public decimal TotalPack { get; set; }
        public decimal ProductTotalQuantity { get; set; }
        public string? Id { get; set; }
    }
}

Caterer/Controllers/PreProductionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Caterer.Data;
using Caterer.Models;
using System.Security.Claims;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.Data.SqlClient;
using System.Data;
using System.Linq;
using Caterer.Data.Migrations;
namespace Caterer.Controllers
{
    public class PreProductionsController : Controller
    {
        private readonly ApplicationDbContext _context;
        public PreProductionsController(ApplicationDbContext context)
        {
            _context = context;
        }
        // GET: PreProductions
        public async Task<IActionResult> Index()

        {
            var userEmail = User.FindFirst(ClaimTypes.Email)?.Value;
            var restaurant = await _context.Restaurants.FirstOrDefaultAsync(r => r.OwnerEmail == userEmail);
            var PreProductions = await _context.PreProductions
            .Where(p => p.RestaurantId == restaurant.RestaurantId)
            .GroupBy(p => p.Id)  
            .Select(g => g.First())  
            .ToListAsync();
            if (PreProductions.Any())
            {
                return View(PreProductions);
            }
            return View();
        }
        //Details
        public async Task<IActionResult> Details(string id)
        {
            var preProduction = await _context.PreProductions
                .FirstOrDefaultAsync(p => p.Id == id);

            if (preProduction == null)
            {
                return NotFound();
            }
            var relatedPreProductions = await _context.PreProductions
                .Where(p => p.MenuItemId == preProduction.MenuItemId)
                .ToListAsync();
            var groupedPreProductions = relatedPreProductions.GroupBy(p => p.MenuItemName).ToList();
            ViewData["GroupedPreProductions"] = groupedPreProductions;
            return View(preProduction);
        }
        //Create
        public IActionResult Create()
        {
            var userEmail = User.FindFirst(ClaimTypes.Email)?.Value;
            var restaurant = _context.Restaurants.FirstOrDefault(r => r.OwnerEmail == userEmail);
            if (restaurant != null)
            {
                var warehouse = _context.Warehouses.Where(p => p.RestaurantId == restaurant.RestaurantId).ToList();
                ViewBag.warehouse = new SelectList(warehouse, "WarehouseId", "WarehouseName");
                var MenuRecipes = _context.MenuRecipes
                 .Where(p => p.RestaurantId == restaurant.RestaurantId)
                 .Select(p => new { p.MenuItemId, p.MenuItemName })
                 .Distinct()
                 .ToList();
                ViewBag.MenuRecipes = new SelectList(MenuRecipes, "MenuItemId", "MenuItemName");
            }
            return View();
        }
        //Get Menu ItemDetails
        public IActionResult GetMenuItemDetails(string id, int warehouseId)
        {
            var menuItemDetails = (from product in _context.Products
                                   join menuRecipe in _context.MenuRecipes
                                   on product.productcode.ToString() equals menuRecipe.Productcode
                                   where menuRecipe.MenuItemId == id && product.WarehouseId == warehouseId
                                   select new
                                   {
                                       RestaurantId = menuRecipe.RestaurantId,
                                       MenuItemId = menuRecipe.MenuItemId,
                                       MenuItemName = menuRecipe.MenuItemName,
                                       MenuCategory = menuRecipe.MenuCategory,
                                       ProductId = menuRecipe.ProductId,
                                       Productcode = menuRecipe.Productcode,
                                       ProductName = menuRecipe.ProductName,
                                       ProductUnit = menuRecipe.ProductUnit,
                                       ProductCategory = menuRecipe.ProductCategory,
                                       ProductType = menuRecipe.ProductType,
                                       MenuRecipeQty = menuRecipe.MenuRecipeQty,
                                       Packs = menuRecipe.Packs,
                                       Quantity = product.Quantity
                                   }).ToList();
            return Json(menuItemDetails);
        }
        //Post  Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(string PreProductionStatus,
      string Type,
      DateTime? PreProductionDate,
      DateTime? ExpiryDate,
      int? WarehouseId,
      List<int> RestaurantId,
      string MenuItemId,
      List<string> MenuItemName,
      List<int> Packs,
      List<string> MenuCategory,
      List<string> ProductId,
      List<string> Productcode,
      List<string> ProductName,
      List<string> ProductUnit,
      List<string> ProductCategory,
      List<decimal> MenuRecipeQty,
      List<string> ProductType,
      List<decimal> TotalQuantity,
      List<decimal> TotalPack,
      List<decimal> ProductTotalQuantity)
        {
            if (ModelState.IsValid)
            {
                List<PreProduction> preproductionData = new List<PreProduction>();
                string latestId = _context.PreProductions.Max(m => m.Id);
                for (int i = 0; i < ProductId.Count; i++)
                {
                    var production = new PreProduction
                    {
                        Id = latestId + 1,
                        WarehouseId = WarehouseId,
                        PreProductionStatus = PreProductionStatus,
                        Type = Type,
                        PreProductionDate = PreProductionDate,
                        ExpiryDate = ExpiryDate,
                        Productcode = Productcode[i],
                        RestaurantId = RestaurantId[i],
                        MenuItemId = MenuItemId,
                        MenuCategory = MenuCategory[i],
                        MenuItemName = MenuItemName[i],
                        ProductId = ProductId[i],
                        ProductName = ProductName[i],
                        ProductCategory = ProductCategory[i],
                        ProductType = ProductType[i],
                        ProductUnit = ProductUnit[i],
                        MenuRecipeQty = MenuRecipeQty[i],
                        Packs = Packs[i],
                        TotalQuantity = TotalQuantity[i],
                        TotalPack = TotalPack[i],
                        ProductTotalQuantity = ProductTotalQuantity[i]
                    };
                    preproductionData.Add(production);
                }
                _context.AddRange(preproductionData);
                await _context.SaveChangesAsync();
                if (PreProductionStatus == "Completed")
                {
                    foreach (var production in preproductionData)
                    {
                        if (!string.IsNullOrEmpty(production.Productcode))
                        {
                            var product = _context.Products
                                .FirstOrDefault(p => p.productcode.ToString() == production.Productcode && p.WarehouseId == production.WarehouseId);

                            if (product != null)
                            {
                                if (production.TotalQuantity != null)
                                {
                                    product.Quantity -= production.TotalQuantity;
                                }
                            }
                        }
                    }
                    await _context.SaveChangesAsync();
                }
                return RedirectToAction("Index");  
            }
            else
            {
                return View();
            }
        }
        // GET: PreProductions/Edit/5
        public IActionResult Edit(string? id)
        {
            ViewBag.Id = id;
            var data = (from product in _context.Products
                        join b in _context.PreProductions
                        on product.productcode.ToString() equals b.Productcode
                        where b.Id == id && b.WarehouseId == product.WarehouseId
                        select new
                        {
                            b.PreProductionStatus,
                            b.PreProductionDate,
                            b.ExpiryDate,
                            b.RestaurantId,
                            b.WarehouseId,
                            b.MenuItemId,
                            b.MenuItemName,
                            b.MenuCategory,
                            b.ProductId,
                            b.Productcode,
                            b.ProductName,
                            b.ProductUnit,
                            b.ProductCategory,
                            b.ProductType,
                            b.MenuRecipeQty,
                            b.Packs,
                            b.TotalQuantity,
                            b.TotalPack,
                            product.Quantity,
                            product.WarehouseName
                        }).ToList();
            var firstpreProduction = data.FirstOrDefault();
            ViewBag.FirstpreProduction = firstpreProduction;
            ViewBag.preproductions = data;
            return View();
        }
        //Post Edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string Id, string PreProductionStatus, string Type, DateTime? PreProductionDate, DateTime? ExpiryDate,

Caterer/Views/PreProductions/Delete.cshtml
@model Caterer.Models.PreProduction

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_CaterersDashboard.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>PreProduction</h4>
    <hr />
    <dl class="row">

        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RestaurantId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RestaurantId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.WarehouseId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.WarehouseId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PreProductionStatus)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PreProductionStatus)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MenuItemId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MenuItemId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MenuItemName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MenuItemName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Packs)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Packs)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MenuCategory)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MenuCategory)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProductId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProductId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Productcode)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Productcode)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProductName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProductName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProductUnit)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProductUnit)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProductCategory)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProductCategory)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MenuRecipeQty)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MenuRecipeQty)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProductType)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProductType)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TotalQuantity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TotalQuantity)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TotalPack)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TotalPack)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="PreProductionId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Caterer/Views/PreProductions/Details.cshtml
@model Caterer.Models.PreProduction

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_CaterersDashboard.cshtml";
    ViewData["Heading"] = "Pre-Production Order";
}

<div class="container-fluid py-8">
    <div class="row">
        <div class="col-10">
            <div class="card">
                <div class="card">
                    <div class="card-header pb-0">
                        <div class="d-flex justify-content-between align-items-center">
                            <h4>Pre-Production Details</h4>
                            <div class="d-flex">
                                <div class="ms-auto">
                                    <a class="btn btn-success btn-sm ms-auto" asp-controller="PreProductions" asp-action="Index">Back to List</a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="card-body">
                        <dl class="row">
                          
                            <dt class="col-sm-2">
                                Menu Category
                            </dt>
                            <dd class="col-sm-10">
                                @Model.MenuCategory
                            </dd>
                            <dt class="col-sm-2">
                                Item Name
                            </dt>
                            <dd class="col-sm-10">
                                @Model.MenuItemName
                            </dd>
                            <dt class="col-sm-2">
                                Prepared Date
                            </dt>
                            <dd class="col-sm-10">
                                @(Model.PreProductionDate.HasValue ? Model.PreProductionDate.Value.ToString("dd-MM-yyyy") : "")
                            </dd>

                            <dt class="col-sm-2">
                                Expiry Date
                            </dt>
                            <dd class="col-sm-10">
                                @(Model.ExpiryDate.HasValue ? Model.ExpiryDate.Value.ToString("dd-MM-yyyy") : "")
                            </dd>

                            <!-- Add other details as needed -->

                        </dl>
                    </div>
                </div>

                <div class="container mt-4">

                    @{

                        @foreach (var group in (List<IGrouping<string, Caterer.Models.PreProduction>>)ViewData["GroupedPreProductions"])
                        {
                            <div class="card">
                                <div class="menu-item-section mt-2">
                                    <h2 class="text-center">@group.Key</h2>

                                    <div class="table-responsive">
                                        <table class="table table-bordered table-striped">
                                            <thead>
                                                <tr class="bg-info text-white">
                                                    <th>S.No</th>
                                                    <th> Name</th>
                                                    <th> Category</th>
                                                    <th>Unit</th>
                                                    <th>Total Pack</th>
                                                    <th>Total Quantity</th>

                                                    <!-- Add other columns based on your requirements -->
                                                </tr>
                                            </thead>
                                            <tbody>
                                                @{
                                                    int counter = 1;
                                                }
                                                @foreach (var relatedProduction in group)
                                                {
                                                    <tr>
                                                        <td>@counter</td>
                                                        <td>@relatedProduction.ProductName</td>
                                                        <td>@relatedProduction.ProductCategory</td>
                                                        <td>@relatedProduction.ProductUnit</td>
                                                        <td>@relatedProduction.TotalPack</td>
                                                        <td>@relatedProduction.TotalQuantity</td>


                                                        <!-- Add other related Production properties -->
                                                        @{
                                                            counter++;
                                                        }
                                                    </tr>
                                                }
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        }
                    }

                </div>
            </div>
        </div>
    </div>
</div>

Caterer/Views/PreProductions/Index.cshtml
@model IEnumerable<Caterer.Models.PreProduction>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_CaterersDashboard.cshtml";
}
<link rel="stylesheet" href="//cdn.datatables.net/1.13.6/css/jquery.dataTables.min.css">

<div class="container-fluid py-8">
    <div class="row">
        <div class="col-lg-12">
            <!-- Increase the width to 12 columns -->
            <div class="card">
                <div class="card-header pb-0">

                    <div class="d-flex justify-content-between align-items-center">
                        <h4>Pre Production List</h4>
                        <div class="d-flex">
                            <div class="ms-auto">
                                <a class="btn btn-success btn-sm ms-auto" asp-controller="PreProductions" asp-action="Create">Add Pre Production</a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table" id="preproduction">
                            <thead>
                                <tr>
                                    <th>S.No</th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.PreProductionDate)
                                    </th>

                                    <th>
                                        @Html.DisplayNameFor(model => model.ExpiryDate)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.MenuItemName)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.TotalPack)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.PreProductionStatus)
                                    </th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @if (Model != null && Model.Any())
                                {
                                    int Slno = 1;
                                    @foreach (var item in Model)
                                    {
                                        <tr>
                                            <td>@Slno</td>
                                            <td>@(item.PreProductionDate.HasValue ? item.PreProductionDate.Value.ToString("dd-MM-yyyy") : "")</td>
                                            <td>
                                                @(item.ExpiryDate.HasValue ? item.ExpiryDate.Value.ToString("dd-MM-yyyy") : "")
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.MenuItemName)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.TotalPack)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.PreProductionStatus)
                                            </td>
                                            <td>
                                                @if (item.PreProductionStatus != "Completed")
                                                {
                                                    <a asp-action="Edit" asp-route-id="@item.Id">
                                                        <i class="fa-solid fa-pen-to-square"></i>
                                                    </a>

                                                }
                                                else
                                                {
                                                    <span style="color: grey;"><i class="fa-solid fa-pen-to-square"></i></span>

                                                }|
                                               
                                                <a asp-action="Details" asp-route-id="@item.Id">
                                                    <i class="fa-solid fa-eye"></i>
                                                </a> |
                                                <a class="text-primary"   onclick="DeleteEditRow(@item.Id);">
                                                    <i class="fa-solid fa-trash"></i>
                                                </a>
                                            </td>
                                        </tr>
                                        Slno++;
                                    }
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@section Scripts {

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.datatables.net/1.13.6/js/jquery.dataTables.js"></script>
    <script>
        function DeleteEditRow(Id) {
            var confirmDelete = confirm("Are you sure you want to delete this item?");

            if (confirmDelete) {
                $.ajax({
                    url: '/PreProductions/DeleteEditRow/' + Id,
                    type: 'POST',
                    data: { id: Id },
                    success: function (result) {
                        alert('Record was deleted successfully..!');
                        location.reload();
                    },
                    error: function (xhr, status, error) {
                        console.log(xhr.responseText);
                        alert('Failed to delete the record.'); // Show an error message if deletion fails
                    }
                });
            }
        }

    </script>
    <script>
        $(document).ready(function () {
            $('.table').DataTable({
                "pageLength": 25
            });
        });
    </script>

    }